apiVersion: apps.dominodatalab.com/v1alpha1
kind: Mutation
metadata:
  name: llm-volume-mount
  namespace: domino-platform
rules:
- enabled: true
  insertVolumeMounts:
    containerSelector:
    - model
    volumeMounts:
    - mountPath: /llm-models
      name: prediction-data-volume
      readOnly: true
      subPath: filecache/e0b94bde-c630-439b-b2b5-651c6569dc9e/llm-models/
  jqSelector:
    query: |
      include "domsed/selectors/common";
      $__kind__ == "Pod" and
      (.metadata.labels."dominodatalab.com/workload-type" | isIn(["ModelAPI"])) and
      (.metadata.labels."dominodatalab.com/workload-type" | isIn(["jane_admin"]) | not)
  matchBuilds: false
- enabled: true
  insertVolumeMounts:
    containerSelector:
    - model
    volumeMounts:
    - mountPath: /llm-models
      name: prediction-data-volume
      readOnly: true
      subPath: filecache/f7923fd7-5935-44a8-bd92-e4193087894e/llm-models/
  jqSelector:
    query: |
      include "domsed/selectors/common";
      $__kind__ == "Pod" and
      (.metadata.labels."dominodatalab.com/workload-type" | isIn(["ModelAPI"])) and
      (.metadata.labels."dominodatalab.com/workload-type" | isIn(["jane_admin"]))
  matchBuilds: false
- cloudWorkloadIdentity:
    assume_sa_mapping: false
    cloud_type: aws
    default_sa: ""
    user_mappings:
      prod-deployer-user-1: prod-deployer-user-1
      prod-deployer-user-2: prod-deployer-user-1
  enabled: true
  labelSelectors:
  - dominodatalab.com/workload-engine=cg2
  matchBuilds: false

      
