apiVersion: apps.dominodatalab.com/v1alpha1
kind: Mutation
metadata:
  name: llm-volume-mount
  namespace: domino-platform
rules:
- insertVolumes:
  - name: prediction-data-volume
    persistentVolumeClaim:
      claimName: domino-shared-store-domino-compute
  insertVolumeMounts:
    containerSelector:
    - model
    volumeMounts:
    - mountPath: "/llm-models"
      name: prediction-data-volume
      readOnly: true
      subPath:  "filecache/e0b94bde-c630-439b-b2b5-651c6569dc9e/llm-models/"
  jqSelector:
    query: |
      include "domsed/selectors/common";
      $__kind__ == "Pod" and
      (.metadata.labels."dominodatalab.com/workload-type" | isIn(["ModelAPI"])) and
      $.inArray(metadata.labels["dominodatalab.com/workload-type"], ["jane_admin"]) !== -1
- insertVolumes:
  - name: prediction-data-volume
    persistentVolumeClaim:
      claimName: domino-shared-store-domino-compute
  insertVolumeMounts:
    containerSelector:
    - model
    volumeMounts:
    - mountPath: "/llm-models"
      name: prediction-data-volume
      readOnly: true
      subPath:  "filecache/e0b94bde-c630-439b-b2b5-651c6569dc9e/llm-models/"
  jqSelector:
    query: |
      include "domsed/selectors/common";
      $__kind__ == "Pod" and
      (.metadata.labels."dominodatalab.com/workload-type" | isIn(["ModelAPI"])) and
      (.metadata.labels."dominodatalab.com/workload-type" | isIn(["jane_admin"]))
- labelSelectors:
  - "dominodatalab.com/workload-engine=cg2"
  cloudWorkloadIdentity:
    cloud_type: azure
    user_mappings:
      jane-admin: jane-admin
    default_sa: ""
      
      
