apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.env.name }}-certificate"
spec:
  secretName: "{{ .Values.env.name }}-certs"
  dnsNames:
  - "{{.Values.env.name}}-proxy-service"
  - "{{.Values.env.name}}-proxy-service.{{ .Values.env.namespace }}"
  - "{{.Values.env.name}}-proxy-service.{{ .Values.env.namespace }}.svc"
  issuerRef:
    name: "selfsigned-{{ .Values.env.name }}"
  duration: {{ .Values.certmanager.duration }}
  renewBefore: {{ .Values.certmanager.renewBefore }}
---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "selfsigned-{{ .Values.env.name }}"
spec:
  selfSigned: {}


