apiVersion: v1
kind: Service
metadata:
  name: {{.Values.env.name}}-proxy-service
spec:
  selector:
    app: triton-proxy
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443

