apiVersion: v1
kind: Service
metadata:
  name: {{.Values.env.name}}-proxy-service
spec:
  selector:
    app: triton-proxy
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000

