#!/bin/bash
# Aviation Disaster Research UI startup script for Domino Apps
#
# This script serves the static frontend and configures it to use the API.
#
# Environment variables:
#   API_URL - URL of the Agentic RAG API (default: https://apps.cloud-dogfood.domino.tech/apps/airline-disaster)
#   UI_PORT - Port to serve UI (default: 8888)
#   PROJECT_PATH - Path to project (default: /mnt)
#   QDRANT_DASHBOARD_URL - URL to Qdrant dashboard (optional, for header link)

set -e

# Configuration
export PROJECT_PATH=${PROJECT_PATH:-/mnt}
export UI_PORT=${UI_PORT:-8888}
export API_URL=${API_URL:-http://localhost:8000}
export QDRANT_DASHBOARD_URL=${QDRANT_DASHBOARD_URL:-http://localhost:6333/dashboard}

export STATIC_DIR="${PROJECT_PATH}/src/agentic_rag/frontend/static"

echo "=============================================="
echo "Aviation Disaster Research UI Startup"
echo "=============================================="
echo ""

echo "Configuration:"
echo "  PROJECT_PATH: ${PROJECT_PATH}"
echo "  STATIC_DIR: ${STATIC_DIR}"
echo "  UI_PORT: ${UI_PORT}"
echo "  API_URL: ${API_URL}"
if [ -n "$DOMINO_API_PROXY" ]; then
    echo "  DOMINO_API_PROXY: ${DOMINO_API_PROXY}"
    echo "  API Auth: Bearer token (via Domino proxy)"
else
    echo "  API Auth: None (local mode)"
fi
if [ -n "$QDRANT_DASHBOARD_URL" ]; then
    echo "  QDRANT_DASHBOARD_URL: ${QDRANT_DASHBOARD_URL}"
fi
echo ""

# Check static directory exists
if [ ! -d "$STATIC_DIR" ]; then
    echo "ERROR: Static directory not found: $STATIC_DIR"
    exit 1
fi

# Create a config.js file with runtime configuration
# Note: DOMINO_API_PROXY is NOT passed to frontend - it's only valid inside the pod
# Browser auth is handled via Domino session cookies, not bearer tokens
echo "Creating runtime configuration..."
cat > "${STATIC_DIR}/config.js" << EOF
// Runtime configuration (generated by startup script)
window.APP_CONFIG = {
    API_URL: '${API_URL}',
    QDRANT_DASHBOARD_URL: '${QDRANT_DASHBOARD_URL}'
};
EOF

# Update index.html to include config.js if not already present
if ! grep -q 'config.js' "${STATIC_DIR}/index.html"; then
    echo "Adding config.js to index.html..."
    sed -i.bak 's|<script src="app.js"></script>|<script src="config.js"></script>\n    <script src="app.js"></script>|' "${STATIC_DIR}/index.html"
    rm -f "${STATIC_DIR}/index.html.bak"
fi

# Update API Docs link in index.html to point to API
echo "Updating API Docs link..."
sed -i.bak "s|href=\"/docs\"|href=\"${API_URL}/docs\"|g" "${STATIC_DIR}/index.html"
rm -f "${STATIC_DIR}/index.html.bak"

# Update Qdrant link in index.html if URL provided
if [ -n "$QDRANT_DASHBOARD_URL" ]; then
    echo "Updating Qdrant dashboard link..."
    sed -i.bak "s|http://localhost:6333/dashboard|${QDRANT_DASHBOARD_URL}|g" "${STATIC_DIR}/index.html"
    rm -f "${STATIC_DIR}/index.html.bak"
fi

echo ""
echo "Starting UI server on port ${UI_PORT}..."
echo "=============================================="
echo ""

# Start Python HTTP server
cd "${STATIC_DIR}"
python -m http.server "${UI_PORT}" --bind 0.0.0.0
