apiVersion: apps.dominodatalab.com/v1alpha1
kind: Mutation
metadata:
  name: add-dataset-model
  namespace: domino-platform
rules:
  - insertVolumeMounts:
      containerSelector:
      - model
      volumeMounts:
      - mountPath: /mnt/data/llmstore
        name: prediction-data-volume
        subPath: filecache/f70fadf6-cb67-44aa-b525-aba22a7e1cab
        readOnly: true
    jqSelector:
      query: |
        include "domsed/selectors/common";
        $__kind__ == "Pod" and
        (.metadata.labels."dominodatalab.com/workload-type" | isIn(["ModelAPI"])) and
        (.metadata.labels."dominodatalab.com/project-id" | isIn(["67ea9c74a9d2124bb43797a5"]))