apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot-only
spec:
  weight: 20
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 5m
    consolidationPolicy: WhenEmpty
  limits:
    cpu: 40
    memory: 320Gi
  template:
    metadata:
      labels:
        dominodatalab.com/domino-node: "true"
        dominodatalab.com/node-pool: spot-only
        dominodatalab.com/capacity-type: spot
    spec:
      expireAfter: Never
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: domino-eks-compute
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64"]
      - key: kubernetes.io/os
        operator: In
        values: ["linux"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot"]
      # Allow multiple families (general, compute, memory optimized)
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values: ["t3", "t4g", "m5", "m6i"]
      # Allow sizes that fit ~2 CPU/6Gi pods but also scale up
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values: ["small", "medium", "large", "xlarge", "2xlarge"]
      startupTaints:
        - effect: NoExecute
          key: ebs.csi.aws.com/agent-not-ready